name       : libogg
version    : 1.3.3
release    : 9
source     :
    - https://github.com/xiph/ogg/archive/v1.3.3.tar.gz : e90a47bb9f9fd490644f82a097c920738de6bfcbd2179ec354e11a2cd3b49806
license    : BSD-3-Clause
summary    : Ogg format library
component  : multimedia.codecs
patterns   :
    - docs : /usr/share/doc
emul32     : yes
optimize   : speed
description: |
    The libogg package contains the Ogg file structure. This is useful for creating (encoding) or playing (decoding) a single physical bit stream.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
