name       : libogg
version    : 1.3.5
release    : 11
source     :
    - https://github.com/xiph/ogg/archive/v1.3.5.tar.gz : f6f1b04cfa4e98b70ffe775d5e302d9c6b98541f05159af6de2d6617817ed7d6
license    : BSD-3-Clause
component  : multimedia.codecs
patterns   :
    - docs : /usr/share/doc
emul32     : yes
optimize   : speed
summary    : Ogg format library
description: |
    The libogg package contains the Ogg file structure. This is useful for creating (encoding) or playing (decoding) a single physical bit stream.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
