name        : libogg
version     : 1.3.2
release     : 7
source     :
    - http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz : 3f687ccdd5ac8b52d76328fbbfebc70c459a40ea891dbf3dccb74a210826e79b
license     : BSD-3-Clause
summary     : Ogg format library
component   : multimedia.codecs
patterns    :
    - docs: /usr/share/doc
emul32      : yes
optimize    : speed
description : |
    The libogg package contains the Ogg file structure. This is useful for creating (encoding) or playing (decoding) a single physical bit stream.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
