name       : libogg
version    : 1.3.3
release    : 8
source     :
    - https://downloads.xiph.org/releases/ogg/libogg-1.3.3.tar.xz : 4f3fc6178a533d392064f14776b23c397ed4b9f48f5de297aba73b643f955c08
license    : BSD-3-Clause
summary    : Ogg format library
component  : multimedia.codecs
patterns   :
    - docs : /usr/share/doc
emul32     : yes
optimize   : speed
description: |
    The libogg package contains the Ogg file structure. This is useful for creating (encoding) or playing (decoding) a single physical bit stream.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
